#!/bin/bash
#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name=`basename $0`

if [ $# -ne 3 ]; then
        echo "${name}: two arguments required"
        exit
fi

devicename="$1"
outputfile="$2"
bucketname="$3"

if [ "${devicename}" == "" ]; then
        echo "${name}: Device name is required"
        exit 1
fi

if [[ "${devicename}" =~ ^/dev/[a-z]{3,4}$ ]]; then
        echo "okay"
else
        echo "${name}: Device pattern does not match"
        exit 1
fi

if [ "${outputfile}" == "" ]; then
        echo "output file path is required"
        exit 1
fi

if [ "${bucketname}" == "" ]; then
        echo "${name}: S3 bucket name is required"
        exit 1
fi

sudo dd if=${devicename} | gzip > ${outputfile}
aws s3 cp ${outputfile} s3://${bucketname}
rm -f ${outputfile}

touch ${outputfile}.done
